# Generated by Django 6.0.1 on 2026-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuetoken',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Completed', 'Completed')], default='Waiting', max_length=20),
        ),
    ]
